displayName=Selective Sound Mixer
author=WiseOldIrony
description=Allows the User to selectively increase or descrease the volume of game sounds
tags=volume,sound,sounds,mixer,area sounds,sound effects,selective,audio
plugins=com.selectivesoundmixer.SelectiveSoundMixerPlugin